# Простая нейронная сеть, делающая прогноз

#### Чистая сеть

In [2]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

#### Передача одной точки данных

In [3]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


#### Вычисление взвешенной суммы входов

In [4]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    
    return output

In [5]:
weights = [0.1, 0.2, 0]
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

#### Получение прогноза

In [6]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

In [7]:
print(pred)

0.9800000000000001


#### Умножает три входных значения на три весовых коэффициента и суммирует результаты.

### Векторная математика 

In [8]:
a = [0, 1, 0, 1]
b = [1, 0, 1, 0]
c = [0, 1, 1, 0]
d = [.5, 0, .5, 0]
e = [0, 1, -1, 0]

In [11]:
print(w_sum(a,b))
print(w_sum(b,c))
print(w_sum(b,d))
print(w_sum(c,c))
print(w_sum(a,b))
print(w_sum(c,e))

0
1
1.0
2
0
0


## NumPy решение

In [21]:
import numpy as np

weights = np.array([0.1, 0.2, 0])
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


#### Функция dot - dot product (скалярное произведение)

## Сеть с несколькими выходами

#### Чистая сеть с несколькими выходами

In [1]:
weights = [0.3, 0.2, 0.9]

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

#### Передача одной точки данных

In [5]:
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


#### Выполнение поэлементного умножения

In [3]:
def ele_mul(number, vector):
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

In [6]:
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


## Прогнозирование с несколькими входами и выходами

#### 1. Чистая сеть с несколькими входами и выходами

In [7]:
weights = [ [0.1, 0.1, -0.3],
          [0.1, 0.2, 0.0],
          [0.0, 1.3, 0.1]]

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

#### 2. Передача одной точки данных

In [11]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


#### 3. Для каждого выхода вычисляется взвешенная сумма входов

In [9]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    
    for i in range(len(vect)):
        output[i]=w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

#### Векторно-матричные умножения.
Находится скалярное произведение вектора и каждой строки матрицы

## Прогнозирование на основе прогнозов

#### Нейронные сети можно накладывать друг на друга

#### 1. Чистая нейронная сеть с несколькими входами и выходами

In [12]:
ih_wgt = [ [0.1, 0.2, -0.1],
          [-0.1, 0.1, 0.9],
          [0.1, 0.4, 0.1]]

hp_wgt = [ [0.3, 1.1, -0.3],
          [0.1, 0.2, 0.0],
          [0.0, 1.3, 0.1]]

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hld = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

Векторы весов хранятся/обрабатываются как векторы-столбцы

#### 2. Прогнозирование в скрытом слое

In [19]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

#### 3. Прогнозирование в выходном слое (и вывод прогноза)

In [18]:
def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


## NumPy подход

In [22]:
hp_wgt = np.array([ [0.1, 0.2, -0.1],
          [-0.1, 0.1, 0.9],
          [0.1, 0.4, 0.1]])
weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)

[-0.1485  0.3475  1.9155]


In [25]:
import numpy as np

a = np.array([0,1,2,3]) # вектор
b = np.array([4,5,6,7]) # вектор
c = np.array([[0,1,2,3], # матрица 
            [4,5,6,7]])

d = np.zeros((2,4)) # матрица 2 х 4, заполненная нулями
e = np.random.rand(2,5) # матрица 2 х 5, заполненная случайными числами от 0 до 1

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.89574667 0.16490524 0.8501528  0.44640897 0.89127815]
 [0.1860802  0.45259381 0.53561729 0.81702759 0.61795509]]


In [31]:
print(a * 0.1) # умножение каждого элемента вектора на 0.1
print(c * 0.2) # каждый элемент матрицы умножается на 0.2
print(a * b) # поэлементное умножение a на b
print(a * b * 0.2) # поэлементное умножение векторов, затем каждый элемент умножается на 0.2
print(a * c) # поэлементное умножение вектора a с каждой строкой матрицы с (имеют одинаковое количество столбцов)

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [33]:
print(a * e)

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [36]:
a = np.zeros((1,4))
b = np.zeros((4,3))
c = a.dot(b)
print(c.shape)

(1, 3)


In [37]:
a = np.zeros((2,4))
b = np.zeros((4,3))
c = a.dot(b)
print(c.shape)

(2, 3)


In [38]:
a = np.zeros((2,1))
b = np.zeros((1,3))
c = a.dot(b)
print(c.shape)

(2, 3)
